[package]
name = "token_launcher"
version = "1.0.0"
authors = []

[addresses]
token_launcher = "0x965f2de54b3037c386d4d28500b0cd5771942b10704a0324c8464348c15ce090"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"