[package]
name = "token_launcher"
version = "1.0.0"
authors = []

[addresses]
token_launcher = "0x305a60232bcdec28ce4777ea394c40bf7e17b016048a2468d14059c54baccaf2"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"