[package]
name = "token_launcher"
version = "1.0.0"
authors = []

[addresses]
token_launcher = "0x8e2ae9d8fe7808bceb9f3568adeeab9ecde3bef7d62be82af72b0f454848aa93"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "6f83bc6d02207298b2dee91133d75538789bf582"